# Generated by Django 4.2.1 on 2023-06-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
