# Generated by Django 4.2.1 on 2023-06-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_film_producers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='film_producer', to='films.producer'),
        ),
    ]
