# Generated by Django 4.2.1 on 2023-06-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_film_producers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='producers',
            field=models.ManyToManyField(related_name='film_producer', to='films.producer'),
        ),
    ]
