# Generated by Django 4.2.1 on 2023-05-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gifs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='gifs',
            field=models.ManyToManyField(blank=True, to='my_gifs.gif'),
        ),
    ]
