# Generated by Django 4.2.1 on 2023-06-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_employee_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
