# Generated by Django 4.2.1 on 2023-06-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_departmentadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentadmin',
            old_name='username',
            new_name='user',
        ),
    ]
