# POST http://localhost:3000/register
# Content-Type: application/json

# {
#     "first": "Ivan",
#     "last": "Ko",
#     "email": "ivan@mail.ru",
#     "username": "ivanko",
#     "password": "secret123"
# }


POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "ivanko",
    "password" : "secret123"
}